import time
import sys 

CURSOR_UP_ONE = '\x1b[1A' 
ERASE_LINE = '\x1b[2K' 

print("\033[1;36;40mTeam 5 is:")
time.sleep(2)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)
print("\033[1;35;40mConnor Coleman")
time.sleep(2)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)
print("\033[1;36;40mAdam Jeske-Stock")
time.sleep(2)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)
print("\033[1;34;40mHiral Patel")
time.sleep(2)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)
print("\033[1;33;40mLeigh Hearne")
time.sleep(2)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)
print("\033[1;34;40mThank you for playing!")
print("\033[1;34;40mThank you for playing!")
print("\033[1;34;40mThank you for playing!")
print("\033[1;34;40mThank you for playing!")
print("\033[1;34;40mThank you for playing!")
time.sleep(1)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)
time.sleep(1)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)
time.sleep(1)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)
time.sleep(1)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)
time.sleep(1)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)
time.sleep(1)
sys.stdout.write(CURSOR_UP_ONE) 
sys.stdout.write(ERASE_LINE)